### ISSUE TITLE
bg colors aren't working

### ISSUE THREAD

**Issue by bskimball** [bradlc/babel-plugin-tailwind-components#13]
version 0.5.10

when using the bg class for any color I am getting the error "Unhandled Rejection (TypeError): Cannot read property 'black' of undefined"

Code
```javascript
// Button.js
import styled from "react-emotion";
import tw from "tailwind.macro";

const Button = styled("button")`
  ${tw`bg-black hover:bg-grey-darkest text-white font-bold py-2 px-4 rounded`};
`;

export default Button;
```

**Comment by bradlc** [comment]
Hey @bskimball 

My best guess is that you don’t have `backgroundSize` in your Tailwind config (https://tailwindcss.com/docs/background-size/)

This is a relatively recent addition to Tailwind (previously you couldn’t customise background sizes) and currently the babel plugin expects it to exist in your config, but I am hoping to improve the error handling soon.

**Comment by bskimball** [comment]
Thanks @bradlc works like a charm.

**Comment by bradlc** [comment]
No problem! Glad it’s working.
