### ISSUE TITLE
Uknown property name for border radius sides

### ISSUE THREAD

**Issue by lukemcdonald** [bradlc/babel-plugin-tailwind-components#16]
When [rounding sides separately](https://tailwindcss.com/docs/border-radius/#rounding-sides-separately) using `.rounded-{t|r|b|l}{-size?}`, the output displays a single unknown property.

For example, the CSS output when using `rounded-t`:

```CSS
border-top-radius: .25rem;
```

The output should be:

```CSS
border-top-left-radius: .25rem;
border-top-right-radius: .25rem;
```

**Comment by bradlc** [comment]
Hey @lukemcdonald. Thanks for reporting this. I have fixed it on the [`next` branch](https://github.com/bradlc/babel-plugin-tailwind-components/tree/next) which I will be tagging on npm this week.
