### ISSUE TITLE
Support for focus-within?

### ISSUE THREAD

**Issue by lusid** [bradlc/babel-plugin-tailwind-components#17]
I've added the focus-within module to the list of modules for borderColors in the tailwind.js config file. 

If I execute this code:
```
console.log(tw`border-b-2 border-grey-light focus-within:border-teal`);
```

I get the following result:
```
{
  "borderBottomWidth": "2px",
  "borderColor": "#dae1e7",
  "@media (min-width: undefined)": {
    "borderColor": "#4dc0b5"
  }
}
```

I know this works when I integrate Tailwind in webpack using postcss, but it doesn't seem to work with this babel plugin.

Also, as an aside, what is the proper way to add these?

```
@tailwind preflight;
@tailwind components;
@tailwind utilities;
```

**Comment by bradlc** [comment]
Hey @lusid 

I'm going to close this issue in favour of #20 which will cover adding `focus-within`

The plugin does not support Tailwind directives. If you want the Tailwind preflight/base styles you will have to add them yourself. How you'd do that depends on which CSS-in-JS solution you are using.
