### ISSUE TITLE
How to pass variables in?

### ISSUE THREAD

**Issue by pkrogel-kws** [bradlc/babel-plugin-tailwind-components#19]
Is there any way to pass variables in?

I know this isn't correct, but something like:

```
const Button = styled('button')`
  ${props=> tw`font-mono text-sm text-${props.textColor} hover:text-${props.textColorHover}`};
`
```

**Comment by joeldbirch** [comment]
Same question. I guess you found an answer for this. May I ask what it was, please?

**Comment by muhghazaliakbar** [comment]
@pkrogel-kws Did you found the solution?

**Comment by bradlc** [comment]
The plugin doesn't support class name interpolation. e.g. `text-${props.foo}`

**Comment by joulse** [comment]
Hey @bradlc 👋, I'm very interested! Is't planned to support class name interpolation one day?
