### ISSUE TITLE
Is .container functional in v1?

### ISSUE THREAD

**Issue by azdanov** [bradlc/babel-plugin-tailwind-components#23]
I've been giving a try to the new version without any issue until `.container`.

It doesn't seem to work. Leaving empty stylesheet.

**Comment by bradlc** [comment]
Hey @azdanov. Plugins are not supported, sorry. I’ll look at making that more clear in the readme.

**Comment by azdanov** [comment]
@bradlc I'm curious what are the technical reason for this limitation, and what other plugins Tailwind CSS has?

**Comment by bradlc** [comment]
I should correct my previous comment: in more recent versions of Tailwind technically _everything_ is a plugin. I guess what I really mean is that the babel plugin **doesn’t support components (like `.container`) or _third-party_ plugins**

I don’t think this project will ever support components, but there _might_ be a way to support utilities created by third-party plugins.

**Comment by sanishkr** [comment]
Any Update on Supporting third party/custom plugins of tailwind in macros.
