### ISSUE TITLE
Is group-hover supported in styled components?

### ISSUE THREAD

**Issue by shawnmmatthews** [bradlc/babel-plugin-tailwind-components#25]
I have added group-hover under the visibility module array in tailwind.js. I have then added it in my styled component as
```
 const Hover = styled.div’
  ${tw ‘invisible group-hover:visible’};
‘
```
 It however doesn’t seem to be applying. All other tailwind styling is working as expected. Is there any thing I need to specifically do to get group-hover working?

**Comment by bradlc** [comment]
Hey @shawnmmatthews 

`group-hover` is supported in the `tailwind.macro` alpha, which you can try if you’re using Tailwind v1: `npm install tailwind.macro@next`

```js
import tw from 'tailwind.macro';

const Hover = tw.div’invisible group-hover:visible’;
```

**Comment by shawnmmatthews** [comment]
Thanks!
