### ISSUE TITLE
emotion source maps

### ISSUE THREAD

**Issue by bradlc** [bradlc/babel-plugin-tailwind-components#30]
I'm still getting the same output as before. My hunch is that it has to do with the babel-plugin-macros.config.js file.

Here's the contents of my config file (located at my client root, its definitely getting read as my server will bomb if I replace '@emotion/styled/macro' with a typo):
```js
module.exports = {
  tailwind: {
    styled: '@emotion/styled/macro'
  }
}
```
(also tried without the /macro suffix)

and here's a snippet from my test page:
```js
import tw from 'tailwind.macro'
import styled from '@emotion/styled/macro'

...

const TailwindHeading = styled.h2`
  ${tw`text-indigo-600`};
`

const NewSyntax = tw.h2`
  text-indigo-600
`

...

<TailwindHeading>
  Tailwind + Emotion Test
</TailwindHeading>
<NewSyntax>
  New Syntax Test
</NewSyntax>
```

And here's what I see in the chrome inspector -- the TailwindHeading styles link to my source code (index.js), while the NewSyntax element is referencing the `<style>` element directly. (I've also tested with the css object style, and that works as well, but I omitted it from this example to try to reduce noise)

<img width="1432" alt="Screen Shot 2019-05-27 at 3 19 41 PM" src="https://user-images.githubusercontent.com/223493/58438189-2b820580-8093-11e9-8f8c-4247231cc5b6.png">

<img width="1439" alt="Screen Shot 2019-05-27 at 3 19 52 PM" src="https://user-images.githubusercontent.com/223493/58438191-3046b980-8093-11e9-92bb-b3a323e42cee.png">

And here is the raw babel output for the two different styled syntaxes (notice the TailwindHeading element has the additional sourceMappingURL defined, while the NewSyntax element does not):

```js
  var TailwindHeading = Object(_emotion_styled_base__WEBPACK_IMPORTED_MODULE_3__["default"])("h2", {
    target: "evcvfon0",
    label: "TailwindHeading"
  })(Object.assign(tailwind_macro_utils_umd_js__WEBPACK_IMPORTED_MODULE_4___default.a.resolveStyle(_tailwindConfig, [{
    "prop": "color",
    "config": "textColor"
  }, {
    "prop": "fontSize",
    "config": "fontSize"
  }], "indigo-600")), ";" + ( false ? undefined : "/*# sourceMappingURL=**omitted** */"));

  var NewSyntax = Object(_emotion_styled_base__WEBPACK_IMPORTED_MODULE_3__["default"])("h2", {
    target: "evcvfon1",
    label: "NewSyntax"
  })(Object.assign(tailwind_macro_utils_umd_js__WEBPACK_IMPORTED_MODULE_4___default.a.resolveStyle(_tailwindConfig, [{
    "prop": "color",
    "config": "textColor"
  }, {
    "prop": "fontSize",
    "config": "fontSize"
  }], "indigo-600")));

  return react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(react__WEBPACK_IMPORTED_MODULE_5___default.a.Fragment, null, react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(TailwindHeading, {
    __source: {
      fileName: _jsxFileName,
      lineNumber: 54
    },
    __self: this
  }, "Tailwind + Emotion Test"), react__WEBPACK_IMPORTED_MODULE_5___default.a.createElement(NewSyntax, {
    __source: {
      fileName: _jsxFileName,
      lineNumber: 57
    },
    __self: this
  }, "New Syntax Test"));
```

I also did a test where I removed the styled.h2`` (TailwindHeading) element and styled import, with the same results -- the returned fragment has the `__source` key, but the initial creation of the element does not have the sourceMappingURL comment.

One last thing that has me puzzled is that the other syntaxes sourcemaps are working fine regardless of whether I define the babel-plugin-macros.config.js file. I'm not sure if this is due to some defaults working out of the box, or if there is something incorrect with my config which is the root issue.

_Originally posted by @apolzon in https://github.com/bradlc/babel-plugin-tailwind-components/issues/20#issuecomment-496303829_

**Comment by bradlc** [comment]
@apolzon Thanks for reporting this. After looking into it properly I found the issue: the source location info was not being carried over to the new AST nodes.

Please could you try `v1.0.0-alpha.10` (`npm install tailwind.macro@next`) and confirm that this has fixed the source map issue?

**Comment by apolzon** [comment]
You rock! It works great :)

I experimented with all the different invocations of the tw literal I could think of, and there is one other that's still not outputting sourcemaps, which is using the tw literal directly (ie, by assigning to the css prop). I'll open a separate issue for that use-case, but if its outside of the intended use of this plugin, feel free to delete it.
