### ISSUE TITLE
[QUESTION] Any possibility to adapt it to `linaria`?

### ISSUE THREAD

**Issue by Viperwow** [bradlc/babel-plugin-tailwind-components#43]

**Comment by phmngocnghia** [comment]
@Viperwow linaria can be used in conjunction with postcss to support tailwind directive @apply.

The syntax will look like like the image bellow.
![image](https://user-images.githubusercontent.com/36730355/66474930-7b022480-eabc-11e9-8abc-ef767e5de7a9.png)

**Comment by Viperwow** [comment]
This is close enough to what I'm looking for! Thanks!
