### ISSUE TITLE
Errant console.log

### ISSUE THREAD

**Issue by josiahdahl** [bradlc/babel-plugin-tailwind-components#6]
Hi @bradlc - I just started using your plugin and it's working great so far. I was trying to get around an issue integrating with Storybook and switched from using the `tailwind.macro` explicit import to the implicit import with `babel-plugin-tailwind-components` in my `.babelrc`.

I noticed some additional logs in the console and found that one had been left here https://github.com/bradlc/babel-plugin-tailwind-components/blob/master/src/index.js#L19. If you can remove it whenever you do your next release that'd be great!

**Comment by bradlc** [comment]
Hey @josiahdahl, thanks for the heads up. I will remove it later today!

**Comment by bradlc** [comment]
Gone in `0.5.4`
