### ISSUE TITLE
[Bug] Parser: border-width and width-x/x negative-margin

### ISSUE THREAD

**Issue by TomPichaud** [bradlc/babel-plugin-tailwind-components#8]
Hello,

I'm trying to use your plugin with [Gatsby](https://github.com/gatsbyjs/gatsby) and Emotion, but I've found few critical issues, wondering if there is any other.

• `border` should output the default `border-width: 1px;` instead of nothing. Don't know where this is coming from...

• `width-1/2` should output `width: 50%;` instead of `width: 0.25rem;` (I think your parser is only reading the first number `width-1`).
This bug is reproduced with any number.

• Also not working with negative margin.

Both issues are related to the parser I guess.

Any help fixing them please, and maybe code a test for the plugin?

**Comment by bradlc** [comment]
Hey Tom,

The issues with width and negative margins are fixed in `0.5.5`

**Comment by bradlc** [comment]
And border should be all good in version `0.5.10`!
